apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: my-container1
        image: aksacrtcspoc.azurecr.io/poc-1:v1.$BUILD_ID
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: aksacrtcspoc
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: aks1-svc
spec:
  selector:
    app: my-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010
  type: LoadBalancer
